package static

type Genre struct {
    Name string `db:"name"`
}

var All_genres = [...] Genre {
    {Name: "Children's"},
    {Name: "Fratire"},
    {Name: "Lad lit"},
    {Name: "New adult fiction"},
    {Name: "Young adult"},
    {Name: "Battle royal"},
    {Name: "Classic"},
    {Name: "Bildungsroman"},
    {Name: "Encyclopedic"},
    {Name: "Epic"},
    {Name: "Epic poetry"},
    {Name: "Fabulation"},
    {Name: "Folklore"},
    {Name: "Folktale"},
    {Name: "Animal tale"},
    {Name: "Fable"},
    {Name: "Fairy tale"},
    {Name: "Ghost story"},
    {Name: "Legend"},
    {Name: "Myth"},
    {Name: "Parable"},
    {Name: "Personal narrative"},
    {Name: "Urban legend"},
    {Name: "Historical"},
    {Name: "Alternate history"},
    {Name: "Historical fantasy"},
    {Name: "Historical mystery"},
    {Name: "Historical romance"},
    {Name: "Regency romance"},
    {Name: "Nautical fiction"},
    {Name: "Pirate novel"},
    {Name: "Metafiction"},
    {Name: "Metaparody"},
    {Name: "Nonsense"},
    {Name: "Nonsense verse"},
    {Name: "Paranoid"},
    {Name: "Pastoral"},
    {Name: "Philosophical"},
    {Name: "Pop culture"},
    {Name: "Postmodern"},
    {Name: "Realist"},
    {Name: "Hysterical"},
    {Name: "Religious or inspirational"},
    {Name: "Christian"},
    {Name: "Islamic"},
    {Name: "Theological"},
    {Name: "Visionary"},
    {Name: "Satire"},
    {Name: "Horatian"},
    {Name: "Juvenalian"},
    {Name: "Menippean"},
    {Name: "Social and political fiction"},
    {Name: "Libertarian sci-fi"},
    {Name: "Social sci-fi"},
    {Name: "Political thriller"},
    {Name: "Theatre-fiction"},
    {Name: "Thriller"},
    {Name: "Suspense"},
    {Name: "Conspiracy"},
    {Name: "Erotic"},
    {Name: "Legal"},
    {Name: "Financial"},
    {Name: "Political"},
    {Name: "Psychological"},
    {Name: "Romantic suspense"},
    {Name: "Techno-thriller"},
    {Name: "Urban"},
    {Name: "Western"},
    {Name: "Florida"},
    {Name: "Northern"},
    {Name: "Space"},
    {Name: "Western romance"},
    {Name: "Weird West"},
    {Name: "Adventure fantasy"},
    {Name: "Heroic fantasy"},
    {Name: "Lost world"},
    {Name: "Sword-and-sandal"},
    {Name: "Sword-and-sorcery"},
    {Name: "Sword-and-soul"},
    {Name: "Wuxia"},
    {Name: "Nautical"},
    {Name: "Pirate"},
    {Name: "Robinsonade"},
    {Name: "Spy"},
    {Name: "Spy-Fi"},
    {Name: "Subterranean"},
    {Name: "Superhero"},
    {Name: "Survival"},
    {Name: "Swashbuckler"},
    {Name: "Picaresque"},
    {Name: "Burlesque"},
    {Name: "Fantasy"},
    {Name: "Comedy horror"},
    {Name: "Parody"},
    {Name: "Metaparody"},
    {Name: "Sci-fi"},
    {Name: "Surreal comedy"},
    {Name: "Tall tale"},
    {Name: "Tragicomedy"},
    {Name: "Caper"},
    {Name: "Giallo"},
    {Name: "Legal thriller"},
    {Name: "Mystery"},
    {Name: "Cozy mystery"},
    {Name: "City mysteries"},
    {Name: "Detective"},
    {Name: "Gong'an"},
    {Name: "Girl detective"},
    {Name: "Inverted detective story"},
    {Name: "Howcatchem"},
    {Name: "Occult detective"},
    {Name: "Hardboiled"},
    {Name: "Historical mystery"},
    {Name: "Locked-room mystery"},
    {Name: "Police procedural"},
    {Name: "Whodunit"},
    {Name: "Noir"},
    {Name: "Nordic noir"},
    {Name: "Tart Noir"},
    {Name: "Action-adventure"},
    {Name: "Heroic"},
    {Name: "Lost world"},
    {Name: "Subterranean"},
    {Name: "Sword-and-sandal"},
    {Name: "Sword-and-sorcery"},
    {Name: "Wuxia"},
    {Name: "Contemporary"},
    {Name: "Occult detective fiction"},
    {Name: "Paranormal romance"},
    {Name: "Urban"},
    {Name: "Cozy fantasy"},
    {Name: "Dark"},
    {Name: "Fairytale"},
    {Name: "Fantastique"},
    {Name: "Fantasy comedy"},
    {Name: "Bangsian"},
    {Name: "Fantasy of manners"},
    {Name: "Gaslamp"},
    {Name: "Gothic"},
    {Name: "Grimdark"},
    {Name: "Hard"},
    {Name: "High"},
    {Name: "Historical"},
    {Name: "Isekai"},
    {Name: "Juvenile"},
    {Name: "Low"},
    {Name: "Magic realism"},
    {Name: "Mythic"},
    {Name: "Mythopoeia"},
    {Name: "Mythpunk"},
    {Name: "Romantic"},
    {Name: "Science"},
    {Name: "Dying Earth"},
    {Name: "Planetary romance"},
    {Name: "Sword and planet"},
    {Name: "Superhero"},
    {Name: "Supernatural"},
    {Name: "Shenmo"},
    {Name: "Weird fiction"},
    {Name: "New weird"},
    {Name: "Weird West"},
    {Name: "Body"},
    {Name: "Biological"},
    {Name: "Comedy"},
    {Name: "Zombie comedy"},
    {Name: "Erotic"},
    {Name: "Monster erotica"},
    {Name: "Ero guro"},
    {Name: "Ghost stories and ghostlore"},
    {Name: "Gothic"},
    {Name: "Gothic romanticism"},
    {Name: "Dark Romanticism"},
    {Name: "American"},
    {Name: "Southern"},
    {Name: "Southern Ontario"},
    {Name: "Space"},
    {Name: "Suburban"},
    {Name: "Tasmanian"},
    {Name: "Urban"},
    {Name: "Japanese"},
    {Name: "Korean"},
    {Name: "Lovecraftian (or Cosmic)"},
    {Name: "Monster literature"},
    {Name: "Jiangshi fiction"},
    {Name: "Werewolf fiction"},
    {Name: "Vampire literature"},
    {Name: "Psychological"},
    {Name: "Splatterpunk"},
    {Name: "Techno"},
    {Name: "Weird fiction"},
    {Name: "Weird menace"},
    {Name: "Weird West"},
    {Name: "Zombie apocalypse"},
    {Name: "Apocalyptic and post-apocalyptic"},
    {Name: "Christian"},
    {Name: "Comedy"},
    {Name: "Utopian and dystopian"},
    {Name: "Dystopian"},
    {Name: "Cyberpunk"},
    {Name: "Biopunk"},
    {Name: "Dieselpunk"},
    {Name: "Japanese cyberpunk"},
    {Name: "Nanopunk"},
    {Name: "Solarpunk"},
    {Name: "Steampunk"},
    {Name: "Utopian"},
    {Name: "Feminist"},
    {Name: "Gothic"},
    {Name: "Isekai"},
    {Name: "Hard"},
    {Name: "Climate fiction"},
    {Name: "Parallel world"},
    {Name: "Libertarian"},
    {Name: "Mecha"},
    {Name: "Mecha anime and manga"},
    {Name: "Military"},
    {Name: "Soft"},
    {Name: "Anthropological"},
    {Name: "Social"},
    {Name: "Space opera"},
    {Name: "Space Western"},
    {Name: "Spy-Fi"},
    {Name: "Subterranean"},
    {Name: "Tech noir"},
    {Name: "Techno-thriller"},
    {Name: "Science fantasy"},
    {Name: "Dying Earth"},
    {Name: "Planetary romance"},
    {Name: "Sword and planet"},
    {Name: "Superhero"},
    {Name: "Heroic Fantasy"},
    {Name: "Cape Punk"},
    {Name: "Heroic Noir"},
    {Name: "Amish"},
    {Name: "Chivalric"},
    {Name: "Fantasy"},
    {Name: "Contemporary"},
    {Name: "Gay"},
    {Name: "Lesbian"},
    {Name: "Medical"},
    {Name: "Erotic"},
    {Name: "Thriller"},
    {Name: "Romantic fantasy"},
    {Name: "Historical"},
    {Name: "Regency"},
    {Name: "Inspirational"},
    {Name: "Paranormal"},
    {Name: "Time-travel"},
    {Name: "Romantic suspense"},
    {Name: "Western"},
    {Name: "Young Adult"},
    {Name: "Academic"},
    {Name: "Literature review"},
    {Name: "Research article or research paper"},
    {Name: "Scientific"},
    {Name: "Technical report"},
    {Name: "Textbook"},
    {Name: "Thesis"},
    {Name: "Dissertation"},
    {Name: "Bibliography"},
    {Name: "Annotated bibliography"},
    {Name: "Biography"},
    {Name: "Memoir"},
    {Name: "Misery literature"},
    {Name: "Slave narrative"},
    {Name: "Contemporary"},
    {Name: "Neo"},
    {Name: "Consilia"},
    {Name: "Cookbook"},
    {Name: "Creative nonfiction"},
    {Name: "Personal narrative"},
    {Name: "Essay"},
    {Name: "Position paper"},
    {Name: "Journalistic writing"},
    {Name: "Arts"},
    {Name: "Business"},
    {Name: "Data-driven"},
    {Name: "Entertainment"},
    {Name: "Environmental"},
    {Name: "Fashion"},
    {Name: "Global"},
    {Name: "Medical"},
    {Name: "Political"},
    {Name: "Science"},
    {Name: "Sports"},
    {Name: "Technical"},
    {Name: "Trade"},
    {Name: "Video games"},
    {Name: "World"},
    {Name: "Reference work"},
    {Name: "Self-help"},
    {Name: "Obituary"},
    {Name: "Travel"},
    {Name: "Guide book"},
    {Name: "Travel blog"},
    {Name: "True crime"},
}

